tasks:
  - name: Install Apache SuperSet
    init: |
      git clone https://github.com/apache/superset.git
      cd superset
      docker-compose -f docker-compose-non-dev.yml pull
      docker-compose -f docker-compose-non-dev.yml up      
  - name: Open README 
    command: gp open README.md      
  - name: Install Steampipe with RSS Plugin
    command: |
      sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/main/install.sh)"
      steampipe -v
      steampipe plugin install steampipe
      steampipe query "select name from steampipe_registry_plugin;"
      steampipe plugin install rss
      steampipe plugin install csv
      steampipe service start --show-password 
      cp /workspace/gitpod-superset-steampipe-postgresql/steampipe/csv.spc ~/.steampipe/config
      steampipe query "select \"Trip ID\", \"Start date\", \"End date\", \"Destination\" from trips"
      
ports:
  # Apache SuperSet
  - port: 8088
    visibility: public
 # Steampipe/ PostgreSQL
  - port: 9193
    visibility: public